# Fly.io Deployment Configuration
# Install: powershell -Command "iwr https://fly.io/install.ps1 -useb | iex"
# Deploy: fly launch

app = "energy-scan-capture"
primary_region = "fra"  # Frankfurt - oder "iad" für USA

[build]
  [build.env]
    NODE_ENV = "production"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/auth/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Deployment
[deploy]
  release_command = "npm run build"
  strategy = "rolling"

# Secrets (set with: fly secrets set KEY=VALUE)
# GOOGLE_SERVICE_ACCOUNT_EMAIL
# GOOGLE_PRIVATE_KEY
# GOOGLE_SPREADSHEET_ID
