# Railway.app Deployment Configuration
# This file is auto-detected by Railway

# Build Configuration
[build]
  builder = "NIXPACKS"
  buildCommand = "npm install && npm run build"

# Start Configuration  
[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

# Health Check - Use dedicated health endpoint (no auth required)
[healthcheck]
  path = "/api/auth/health"
  interval = 30
  timeout = 10

# Environment Variables (set in Railway Dashboard)
# NODE_ENV=production (auto-set)
# PORT=5000 (auto-set by Railway)
# GOOGLE_SERVICE_ACCOUNT_EMAIL=...
# GOOGLE_PRIVATE_KEY=...
# GOOGLE_SPREADSHEET_ID=...
